
import type { Metadata } from "next";
import "./globals.css"
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Ruth UWAMAHORO | Full-Stack Developer",
  description: "Generated by create next app",
};


// export const metadata: Metadata = {
//   title: "Ruth UWAMAHORO | Full-Stack Developer",
//   description: "Ruth UWAMAHORO is a Rwanda-based Software developer building web and mobile applications and digital productis with Typescript,Javascript, Python and Java.",
//   keywords: [
//     "Ruth UWAMAHORO",
//     "Software Developer",
//     "Software Engineer Rwanda",
//     "Rwanda Developer",
//     "Typescript Developer",
//     "Python Developer",
//     "Java Developer",
//     "React Developer",
//     "Nextjs Developer"
//   ],
//   authors: [{
//     name: "Ruth UWAMAHORO"
//   }],
//   creator: "Ruth UWAMAHORO",
//   openGraph: {
//     title: "Ruth UWAMAHORO | Full-Stack Software Developer",
//     description: "Rwanda-based Full stack Developer building web and mobile applications",
//     type: "website"
//   }
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
